[package]
name = "secrets-cli"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.38", features = ["derive"] }
magic-crypt = "4.0.1"
serde_json = "1.0.140"

[dev-dependencies]
assert_cmd = "2.0.17"
